### ISSUE TITLE
Would be useful to be able to turn off the happy testing for a line

### ISSUE THREAD

**Issue by OvermindDL1** [vic/happy#5]
I have code kind of like:

``` elixir
  def update(conn, %{"uid" => uid_param, "name" => name_param, "pidx" => pidx, "perm" => perm_params} = params) do
    happy_path! do
      # snip
      {redirect, redirect_to} = case Map.get(params, "redirect", nil) do
        "show" -> {"show", permissions_path(conn, :show, uid, name)}
        _ -> {nil, permissions_path(conn, :index, uid)}
      end
      # snip
    end
  end
```

And the matching is completely matched so it is causing a dialyzer issue:

``` elixir
permissions_controller.ex:112: The variable _@8 can never match since previous clauses completely covered the type {'nil' | <<_:32>>,_}
```

I could just split those into two different cases to set to one variable but that is noisy and separates things that I would prefer to have together.  Would it be possible to have a special `tag` like `@already_happy` or something (I've not thought of a name and that is too long) to disable the internal happy case generation for a single expression like that so I could do this instead to make dialyzer happy too?

``` elixir
  def update(conn, %{"uid" => uid_param, "name" => name_param, "pidx" => pidx, "perm" => perm_params} = params) do
    happy_path! do
      # snip
      @already_happy {redirect, redirect_to} = case Map.get(params, "redirect", nil) do
        "show" -> {"show", permissions_path(conn, :show, uid, name)}
        _ -> {nil, permissions_path(conn, :index, uid)}
      end
      # snip
    end
  end
```

Possible names off the top of my head:  `@happy`, `@ignore`, `@nomatch`, etc....

The even better way, the best way, don't use a tag but instead match out the return types of an expression and see if it will always match, and if so then just do not emit the internal case.  Although that would be more difficult to do but would be more correct.

**Comment by vic** [comment]
Thanks for your feature suggestion. It's included now on `v1.3.0`

https://github.com/vic/happy#happy-tag

**Comment by OvermindDL1** [comment]
Looks perfect, I'll test it the next chance I get and close this if no issues found.  :-)

**Comment by OvermindDL1** [comment]
Found a bug, I added `@happy` here:

``` elixir
      @happy {redirect, redirect_to} = case Map.get(params, "redirect", nil) do
        "show" -> {"show", permissions_path(conn, :show, uid, name)}
        _ -> {nil, permissions_path(conn, :index, uid)}
      end
```

And get an error of:

``` elixir
== Compilation error on file web/controllers/auth/permissions_controller.ex ==
** (ArgumentError) expected 0 or 1 argument for @happy, got: 2
    (elixir) lib/kernel.ex:2381: Kernel.do_at/4
    (elixir) expanding macro: Kernel.@/1
    web/controllers/auth/permissions_controller.ex:52: MyServer.Auth.PermissionsController.create/2
    (elixir) expanding macro: Kernel.|>/2
    web/controllers/auth/permissions_controller.ex:48: MyServer.Auth.PermissionsController.create/2
    (elixir) expanding macro: Kernel.|>/2
    web/controllers/auth/permissions_controller.ex:48: MyServer.Auth.PermissionsController.create/2
    (elixir) expanding macro: Kernel.|>/2
    web/controllers/auth/permissions_controller.ex:48: MyServer.Auth.PermissionsController.create/2
    expanding macro: Happy.happy_path!/1
    web/controllers/auth/permissions_controller.ex:48: MyServer.Auth.PermissionsController.create/2
    (elixir) lib/kernel/parallel_compiler.ex:116: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

Appears related to #6 as it is the same error.

**Comment by OvermindDL1** [comment]
Some tests:

``` elixir
iex> defmodule Testering do def t(), do: (quote do happy_path! do {a, b} = case a_var do true -> {:a, :b}; _ -> {:c, :d} end end end |> Macro.expand(__ENV__) |> Macro.to_string) end; Testering.t()
"{a, b} = case(a_var) do\n  true ->\n    {:a, :b}\n  _ ->\n    {:c, :d}\nend"

iex> defmodule Testering do def t(), do: (quote do happy_path! do @happy {a, b} = case a_var do true -> {:a, :b}; _ -> {:c, :d} end end end |> Macro.expand(__ENV__) |> Macro.to_string) end; Testering.t()
** (ArgumentError) expected 0 or 1 argument for @happy, got: 2
    (elixir) lib/kernel.ex:2381: Kernel.do_at/4
    (elixir) expanding macro: Kernel.@/1
             iex: Testering.t/0

iex> defmodule Testering do def t(), do: (quote do happy_path! do @blahblah {a, b} = case a_var do true -> {:a, :b}; _ -> {:c, :d} end end end |> Macro.expand(__ENV__) |> Macro.to_string) end; Testering.t()
** (ArgumentError) expected 0 or 1 argument for @blahblah, got: 2
    (elixir) lib/kernel.ex:2381: Kernel.do_at/4
    (elixir) expanding macro: Kernel.@/1
             iex: Testering.t/0
```

EDIT:  and more:

``` elixir
iex> defmodule Testering do def t(), do: (quote do happy_path! do @happy {a, b} = {:c, :d} end end |> Macro.expand(__ENV__) |> Macro.to_string) end; Testering.t()
** (ArgumentError) cannot set attribute @happy inside function/macro
    (elixir) lib/kernel.ex:2336: Kernel.do_at/4
    (elixir) expanding macro: Kernel.@/1
             iex: Testering.t/0
```

Might be iex oddities though...
