### ISSUE TITLE
illegal pattern

### ISSUE THREAD

**Issue by OvermindDL1** [vic/happy#7]
Given this reduced test:

``` elixir
IO.inspect({:ok, str} when is_binary(str) = get_a_string_or_whatever())
```

It gives an 'illegal pattern' error at compile-time of:

``` elixir
 ** (CompileError) web/controllers/index_controller.ex:8: illegal pattern
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:116: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by OvermindDL1** [comment]
Unsure how fixable this one is, but normal matching without the 'when' works.

**Comment by OvermindDL1** [comment]
Probably should be ignored now that I'm thinking of it, I'd say only top-level ones should be watched for perhaps?
